#
version: "3.7"
#
services:
  #
  front:
    container_name: tgvmax-front
    restart: unless-stopped
    env_file:
    - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tgvmax.loadbalancer.server.port=8081"
      - "traefik.http.routers.tgvmax.rule=Host(`tgvmax.${DNS_MAIN_BASE}`)"
      - "traefik.http.routers.tgvmax.entrypoints=websecure"
      - "traefik.http.routers.tgvmax.tls=true"
      - "traefik.http.routers.tgvmax.tls.certresolver=letsencrypt"
  #
  back:
    container_name: tgvmax-back
    restart: on-failure
    env_file:
    - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tgvmax.loadbalancer.server.port=8080"
      - "traefik.http.routers.tgvmax.rule=Host(`api.tgvmax.${DNS_MAIN_BASE}`)"
      - "traefik.http.routers.tgvmax.entrypoints=websecure"
      - "traefik.http.routers.tgvmax.tls=true"
      - "traefik.http.routers.tgvmax.tls.certresolver=letsencrypt"
    volumes:
      # Database
      - ./tgvmax.sqlite:/usr/src/tgvmax.sqlite
#